server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      dll-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root

security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey
